services:
  mysqldb:
    image: mysql:9.1.0
    platform: linux/arm64/v8
    container_name: mysqlcontainer
    restart: unless-stopped
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: Chatapp
      MYSQL_PASSWORD: Fishki123!
      MYSQL_ROOT_PASSWORD: Fishki123!
      MYSQL_USER: chatuser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeaapcontainer
    build: .
    image: node:alpine3.11
    platform: linux/arm64/v8
    ports:
      - "5001:5001"
    expose:
      - "5001"
    environment:
      DB_HOST: mysqldb
      DB_USER: 'chatuser'
      DB_PASSWORD: 'Fishki123!'
      DB_NAME: Chatapp
      DB_PORT: 3306
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
      SERVICE_PORT: 5001
    depends_on:
        - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
