CREATE DATABASE IF NOT EXISTS Chatapp;
USE Chatapp;

CREATE TABLE IF NOT EXISTS chats (
    id INT PRIMARY KEY AUTO_INCREMENT,
    creatorId INT,
    title VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);