name: 'Check'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Check SECRET_KEY presence
        run: echo "SECRET_KEY is ${SECRET_KEY}"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Run tests
        env:
       
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm test

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Create builder instance
        run: docker buildx create --use --name nodebuilder

      - name: Build Docker image
        run: docker buildx build --platform=linux/arm64/v8 -t myapp:latest --load .

      - name: Save Docker image to file
        run: docker save -o myapp_latest.tar myapp:latest

      - name: Deploy to server
        run: |
            docker stop node || true
            docker rm node || true
            docker run -d --name node -p 5001:5001 \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              myapp:latest
