name: Build and Test with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:9.1.0  # Use MySQL 8.0 or another valid version
        ports:
          - "3306:3306"

    steps:
      # Step 1: Checkout code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the Node.js project
      - name: Build project
        run: npm run build

      # Step 5: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          version: '1.29.2'  # Specify the version of Docker Compose you need

      # Step 6: Start services with Docker Compose
      - name: Start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      # Step 7: Run tests inside Docker container
      - name: Run tests inside Docker container
        run: |
          docker-compose exec nodeapp npm test

      # Step 8: Stop Docker Compose services
      - name: Stop Docker Compose services
        run: docker-compose down

      # Step 9: Check SECRET_KEY
      - name: Check SECRET_KEY presence
        run: echo "SECRET_KEY is ${{ secrets.SECRET_KEY }}"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      # Step 10: Optional - Push Docker image to Docker Hub
      - name: Push Docker image (Optional)
        run: docker-compose push